<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>next-button</name>
   <tag></tag>
   <elementGuidId>de6898ea-6460-4818-96f5-5cfd3f78fed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[1]/div/main/div[1]/div[1]/div/div[1]/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[1]/div/main/div[1]/div[1]/div/div[1]/div/div[2]/div/div/button</value>
   </webElementProperties>
</WebElementEntity>
